spring:
  application:
    name: springboot-nyano

  datasource:
    url: jdbc:mysql://localhost:33336/shopdev
    username: root
    password: 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    port: 465
    host: hihi
    username: t
    password: t
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true